### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by tofumarinado** [jeremyckahn/js-project-starter#1]
When i run `npm install`, i get this error:

```
$ npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm ERR! Linux 4.4.0-97-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Not found : @jeremyckahn/minami
npm ERR! 404 
npm ERR! 404  '@jeremyckahn/minami' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'modern-js-project'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/wextia/tmp/modern-js-project/npm-debug.log
```

**Comment by jeremyckahn** [comment]
Hi @wextia, thanks for opening this ticket!  This is definitely a strange issue, because `@jeremyckahn/minami` [is indeed published](https://www.npmjs.com/package/@jeremyckahn/minami).  Just to sanity check, please try running this and see if npm can at least find the module in a more direct fashion:

```
cd /tmp && npm i @jeremyckahn/minami
```

If it still doesn't find the module, perhaps try upgrading your version of npm?  Maybe there's some issue with Linux and [scoped npm packages](https://docs.npmjs.com/getting-started/scoped-packages)?  For comparison's sake, I am on OS X with npm 5.4.2.

**Comment by jeremyckahn** [comment]
I just figured the issue out — the `@jeremyckahn/minami` package was private.  Apparently [NPM makes scoped packages public by default](https://docs.npmjs.com/cli/access#details), which I was not aware of, and I have corrected the access settings in NPM and corrected the required version for this project.  Thanks again for reporting, @wextia!

**Comment by tofumarinado** [comment]
Anytime! Thanks for looking into it :)
